[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InfiniteOpt = "20393b10-9daf-11e9-18c9-8db751c92c57"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Distributions = "0.25"
Documenter = "1.5"
InfiniteOpt = "0.5"
Ipopt = "1.6"
HiGHS = "1"
julia = "1.10"
JuMP = "1.23"
Literate = "2.18"
Plots = "1"
SpecialFunctions = "2"
