name: Documentation
on:
  push:
    branches: [master]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip docs]')"
    env:
      GKS_ENCODING: "utf8"
      GKSwstype: "100"
      PLOTS_TEST: "true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6' # Build documentation on Julia 1.6
      - name: Install plotting dependencies # For enabling GR.jl (used by Plots.jl)
        run: sudo apt-get install -y qt5-default
      - name: Install julia dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Plot friendly RUNCMD # needed to enable Plots.jl correctly
        run: echo "RUNCMD=xvfb-run --auto-servernum julia" >> $GITHUB_ENV
      - name: Fix curl mismatch # (https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ)
        run: |
             sys_libcurl="$(find /usr/lib/x86_64-linux-gnu -maxdepth 1 -type d -name "libcurl.so.*" | sort -n | tail -1)"
             julia_lib="$(dirname "$(which julia)")/../lib/julia"
             julia_libcurl="$(find $julia_lib -maxdepth 1 -type d -name "libcurl.so.[0-9]" | sort -n | tail -1)"
             sudo rm $julia_libcurl
             sudo ln -s $sys_libcurl $julia_libcurl
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: $RUNCMD --project=docs/ --color=yes docs/make.jl
  Skip:
    if: "contains(github.event.head_commit.message, '[skip docs]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip DocsðŸš«
        run: echo skip doc build
